### PR TITLE
Adding updated info on Attributes

### PR DESCRIPTION
**Pull request by blaine-O**

### CODE REVIEW

**Comment by blaine-O** [comment]
@dshurt Not sure where the conflict is, did the last changes merge?

**Comment by dshurt** [comment]
The last change merged fine.  Cameron made some changes afterwords so that may have conflicted.  You'l l have to pull down the latest from di2e:release/v2.2  and then fix the conflict in order to resolve.   If you want I can try to manually apply the changes to current one?

**Comment by dshurt** [comment]
Never-mind, looks like I was able to resolve it from githubs online tool.

**Comment by blaine-O** [comment]
@dshurt Thanks!

**Pull request merged**
