### PR TITLE
Feature/STORE-1242/STORE-1340

### PR DESCRIPTION
**Pull request by FlammableFork**

### CODE REVIEW

**Comment by FlammableFork** [comment]
Are you talking about the fact that the eventType may not be sorted exactly the same as the eventTypeDescription, because they are not the exact same string?  The event type description is generated on a per request basis, but it is hard coded in the NotificationEventType class.  With what is hard coded, the sorting will be exactly the same.  Doing things this way will let us leave the remote sorting in place, instead of requesting all records and sorting locally.  How many events are there in production?  I would think that the best approach would be to have the description in the database, and we could sort on it.  Is there a reason that it is not in the database?

**Comment by dshurt** [comment]
"Are you talking about the fact that the eventType may not be sorted exactly the same as the eventTypeDescription, because they are not the exact same string? "

Yes, what I'm concerned about is that the description can change in the future and then it breaks the sorting unexpectedly.  Creates a hidden issue.  The NotificationEventType  is a system table which means it under developer control however, it still would be confusing as to why it's breaking if the description changes.

"How many events are there in production?"  there's no very many <30 and they only persist for a short time period.

"Is there a reason that it is not in the database?" 

Yes, putting the description in the database would cause maintenance issues with existing data and going forward.

However, I've been thinking about the situation and I think for this case it would be good to change the UI to display the Event Type and not the Event Type Description.  And then we'll update the description to be more detailed and have a tooltip on the text the shows the detailed description.  The Event Type code are reasonably descriptive.  The sorting can then operate directly on the event type with the current handling.   The advantage the user can see a longer description of what that event is.  We also need to update the NotificationPanel (User) as well to match.

**Comment by FlammableFork** [comment]
I have committed the changes to change the data index and create a tooltip for the description.

**Comment by dshurt** [comment]
Looks good

**Pull request merged**
